#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-moped
Version  : 2.0.7
Release  : 4
URL      : https://rubygems.org/downloads/moped-2.0.7.gem
Source0  : https://rubygems.org/downloads/moped-2.0.7.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
Moped [![Build Status](https://secure.travis-ci.org/mongoid/moped.svg?branch=master)](http://travis-ci.org/mongoid/moped) [![Code Climate](https://codeclimate.com/github/mongoid/moped.svg)](https://codeclimate.com/github/mongoid/moped) [![Coverage Status](https://coveralls.io/repos/mongoid/moped/badge.png?branch=master)](https://coveralls.io/r/mongoid/moped?branch=master)
========

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n moped-2.0.7
gem spec %{SOURCE0} -l --ruby > rubygem-moped.gemspec

%build
gem build rubygem-moped.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
moped-2.0.7.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/moped-2.0.7.gem
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/README.md
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/address.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/authenticatable.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection/manager.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection/socket.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection/socket/connectable.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection/socket/ssl.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection/socket/tcp.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection/sockets.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/cursor.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/database.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/executable.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/failover.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/failover/disconnect.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/failover/ignore.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/failover/reconfigure.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/failover/retry.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/indexes.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/instrumentable.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/instrumentable/log.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/instrumentable/noop.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/loggable.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/operation.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/operation/read.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/operation/write.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/protocol.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/protocol/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/protocol/commands.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/protocol/commands/authenticate.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/protocol/delete.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/protocol/get_more.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/protocol/insert.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/protocol/kill_cursors.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/protocol/message.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/protocol/query.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/protocol/reply.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/protocol/update.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/query.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/read_preference.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/nearest.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary_preferred.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/secondary.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/secondary_preferred.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/selectable.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/readable.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/retryable.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/session.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/uri.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/write_concern.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/write_concern/propagate.rb
/usr/lib64/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/write_concern/unverified.rb
/usr/lib64/ruby/gems/2.3.0/specifications/moped-2.0.7.gemspec
